# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -o app  -v ./cmd/

    - name: Up database
      run: docker-compose up -d

    - name: Download migrate
      run: wget -qO- https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz

    - name: Run migrate
      run:  migrate -path database/migrations/ -database "mysql://user:1234@tcp(localhost:3306)/go_gin_gonic?charset=utf8mb4&parseTime=True&loc=Local" up

    - name: Test
      run: go test -v ./...
